version: '3.4'

services:
  store.api:
    image: storeapi:dev
    container_name: Store.Api_1_1
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Store.Api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - C:\Users\navi3\Source\Repos\DN_CRUD_3\Store\CRUD_V3\Store.Api:/app
      - C:\Users\navi3\Source\Repos\DN_CRUD_3\Store\CRUD_V3:/src
      - C:\Users\navi3\vsdbg\vs2017u5:/remote_debugger:rw
      - C:\Users\navi3\.nuget\packages\:/root/.nuget/packages:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/src/../../../../../../Ismael/Source/Repos/DN_CRUD_3/Store/CRUD_V3/Store.Api/bin/Debug/net6.0/Store.Api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true